### ISSUE TITLE
Package is broken when customizing vite extensions

### ISSUE THREAD

**Issue by BasilaryGroup** [wobsoriano/vuetify-use-dialog#2]
node: v16.18.1
vue: 3.2.45
vuetify: 3.1.2
vite: 4.0.4
vuetify-use-dialog: 0.1.8

When run in development environment vite fails on an import validation check.

$ npm run dev

```
[plugin:vite:import-analysis] Failed to resolve import "./utils" from "node_modules\vuetify-use-dialog\dist\ConfirmDialog.vue". Does the file exist?
C:/Project/client/node_modules/vuetify-use-dialog/dist/ConfirmDialog.vue:4:33
2  |  import { VBtn, VCard, VCardActions, VCardText, VCardTitle, VDialog, VSpacer, VThemeProvider } from "vuetify/components";
3  |  import { computed, inject, onMounted, ref } from "vue";
4  |  import { ConfirmDialogKey } from "./utils";
   |                                    ^
5  |  const _sfc_main = /* @__PURE__ */ _defineComponent({
6  |    __name: "ConfirmDialog",
    at formatError (file:///C:/Project/client/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41235:46)
    at TransformContext.error (file:///C:/Project/client/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41231:19)
    at normalizeUrl (file:///C:/Project/client/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:39540:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TransformContext.transform (file:///C:/Project/client/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:39673:47)
    at async Object.transform (file:///C:/Project/client/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41506:30)
    at async loadAndTransform (file:///C:/Project/client/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:39313:29
```

**Comment by BasilaryGroup** [comment]
Looks like [src/ConfirmDialog.vue](https://github.com/wobsoriano/vuetify-use-dialog/blob/main/src/ConfirmDialog.vue) is sensitive to the local vite configuration.

My vite configuration file which causes `src/ConfirmDialog.vue` to fail to find the `./utils` file.

```ts
export default defineConfig({
  plugins: [vue(), VueI18nPlugin({})],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    },
    extensions: ['.js', '.vue', '.json']
  },
  assetsInclude: ['**/*.md']
})
```

If I add `.mjs` to the extensions then everything works.

```ts
export default defineConfig({
  plugins: [vue(), VueI18nPlugin({})],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    },
    extensions: ['.js', '.vue', '.json', '.mjs']
  },
  assetsInclude: ['**/*.md']
})
```

**Comment by MaksOta** [comment]
mjs is in the defaults anyway. 
according to the documentation https://vitejs.dev/config/shared-options.html#resolve-extensions

**Comment by wobsoriano** [comment]
Not sure how to go about this. Even vuetify uses mjs in all of its exports

https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/package.json#L53
